   0 REM THE GAMES OF THE GAMES
   0 BORDER NOT PI: PAPER NOT PI: INK NOT PI: CLEAR 
   0 PRINT AT 21,0; PAPER 1; INK 7;"MAGNUM PRESENTA........"; FLASH 1;"THE GAMES": PRINT AT 0,0
   0 LOAD ""SCREEN$ : PAPER 6: INK 6 : BORDER 1 : PRINT AT 1,0: LOAD ""
